# Generated by Django 2.2 on 2020-05-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200517_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
